name: grammafy
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.5
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^8.1.3
  bloc_test: ^9.1.1
  get_it: ^7.6.3
  path_provider: ^2.1.5
  dio: ^5.2.1+1
  hydrated_bloc: ^9.1.2
  logger: ^2.0.2+1
  bloc: ^8.1.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  injectable: ^2.3.2
  auto_route: ^7.8.4
  sqflite: ^2.3.3+1
  fpdart: ^1.1.1
  animated_text_kit: ^4.2.3
  flutter_dotenv: ^5.2.1
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  freezed: ^2.3.3
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  auto_route_generator: ^7.3.2
  mockito: ^5.4.4
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/

  fonts:
    - family: Golos
      fonts:
        - asset: fonts/golos_medium.ttf
        - asset: fonts/golos_regular.ttf
